### ISSUE TITLE
Size graphical editor appropriately on initial diagram load

### ISSUE THREAD

**Issue by nk-coding** [hylimo/hylimo#11]
Currently, the graphical editor just loads with default position (0, 0) and zoom 1.
However, depending on the loaded diagram, this is not an appropriate viewport.
When initially loading a diagram, an appropriate viewport should be calculated and used.
Additionally, potentially do this when adding new diagram elements (not sure yet if this is a good idea)

**Comment by delvh** [comment]
Do we already store the dimension information of the whole diagram, or do we need to calculate it?
If we don't store it already, how does for example the export work?
Does it calculate the dimension on demand?

**Comment by nk-coding** [comment]
It's calculated on demand, we just need to add this at the right place in the frontend

**Comment by nk-coding** [comment]
Just an idea: I think it would be reasonable to do this too when the diagram changed "too much"
The idea is, if you copy paste a new diagram, likely the diagram will change significantly all at once, and one would probably an automatic zoom and pan to fit the new diagram.
Of course if you just add one class or so you don't want this to happen, so we would need some kind of threshold, maybe some fraction of the diagram elements which would need to be added/removed at once?

**Comment by delvh** [comment]
> threshold: Copy and Paste Action?

**Comment by nk-coding** [comment]
> > threshold: Copy and Paste Action?

Certainly possible, however there are some technical and conceptual problems
- imagine you want to copy paste a single class, in this case you probably don't want the graphical view to show the full diagram again, as you likely want to now move that class you just pasted to a (likely near) location
  - or imagine you just paste the name of a class / property etc., the important part is that the change needs to be significant enough
- this would move the trigger of this thing out of the `diagram-ui`, which would make it certainly harder to implement (need for protocol addition)
- as this is not captured by the LSP, this would need to be an addition every implementation (e.g. website, VSCode plugin) would need to add manually
