### ISSUE TITLE
Add segments to associations graphically

### ISSUE THREAD

**Issue by nk-coding** [hylimo/hylimo#21]
- Add a way to add new intermediate points to associations graphically.
- for the time being, it is sufficient if associations created using the builder DSL (e.g. ``start(0).line(end(0))` ) are supported
- will likely require new kind of edit: adding parameters to a function
  - maybe we add tracking of missing parameters
  - if used in replace edits, this would allow adding missing parameters, e.g. to the `label` function
- open questions
  - what graphical action causes a new point
    - I would prefer double click, however already used for navigate to source
    - Ctrl + click used for multi-selection
    - shift + click still available

**Comment by delvh** [comment]
<kbd>Right click</kbd> on a segment > context menu > `insert segment here`?

**Comment by nk-coding** [comment]
at some point we will likely need to add a context menu and then this will be an option too
however as this is sth you really need a lot, I would like to have sth faster too (ideally one modifier + click)
