### ISSUE TITLE
Trailing comma support

### ISSUE THREAD

**Issue by nk-coding** [hylimo/hylimo#35]
The trailing comma support seems to be broken (shame on me, I didn't test this sufficiently when reviewing the PR)
None of these work:
```
classDiagram {
    println(1,)
}
```
```
classDiagram {
    [1,]
}
```
```
classDiagram {
    (a,) = args
}
```

**Comment by delvh** [comment]
Wait, which PR do you mean?
#3?

**Comment by nk-coding** [comment]
The PR associated with that issue

**Comment by delvh** [comment]
Regarding trailing commas: That seems to be an issue with `AT_LEAST_ONE_SEP`/`MANY_SEP`.
Here's an example of the Java syntax in Chevrotain with this property: https://github.com/jhipster/prettier-java/blob/d18871d1ec1cc2c4b841d13d4e3e432dc7133d8b/packages/java-parser/src/productions/classes.js#L577-L607
Their solution seems to be not to use the methods but to do a manual `MANY(ONE, OPTION[comma])`.
Thus, if we want this, we would probably need to throw out the `…_SEP` methods
