### ISSUE TITLE
Lexical improvements

### ISSUE THREAD

**Issue by nk-coding** [hylimo/hylimo#90]
- unicode support for characters and strings
  - the typical approach for this is to include all unicode characters except the ones which need replacing
- unicode support for identifiers
  - use ID_START and ID_CONTINUE
- template strings
  - use the `$` syntax known from js an many other languages
  - in regular strings
  - make `$` escapable

**Comment by delvh** [comment]
Regarding edge cases:
All unicode chars are interpreted as non-special signs.
That means, `user你好aa -- bob` is a single identifier, and not a special char.
